#서버 설정
server:
  port: 8080
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true

#데이터베이스 설정
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://43.200.90.166:56424/GOLDENAGE
    username: GOLDENAGE
    password: C##GOLDENAGE

#파일 업로드 시 첨부파일 크기 지정
  servlet:
    multipart:
      max-file-size: 120MB
      max-request-size: 120MB

# 타임리프 설정
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html

# 작업 편의를 위해 추가한 devtool. 브라우저 새로 고침으로 정적 리소스 업데이트가 가능합니다.
  spring:
    devtools:
      livereload:
        enabled: true
    freemarker:
      cache: false
    thymeleaf:
      cache: false


# 파일, 이미지 업로드시 저장될 폴더 설정
  web:
    resources:
      static-locations: classpath:/upload/
      image:
        image-dir: src/main/resources
      devtools:
        livereload:
          enabled: true
        remote:
          restart:
            enabled: true

#mybatis config
mybatis:
  mapper-locations: mappers/**/*.xml
  type-aliases-package: com.goldenage.project.login.model.dto,
                        com.goldenage.project.company.model.dto





